apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-busybox-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-busybox-deployment  # Adjust this if it's not part of a deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale when average CPU utilization hits 50%s